[package]
name = "oppai-sys"
version = "0.1.0"
authors = ["Michael Zhang <iptq@protonmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
path = "lib.rs"

[build-dependencies]
bindgen = "0.51"
cc = { version = "1.0", features = ["parallel"] }